#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

use File::Slurper qw(read_text);
use Finance::Bank::ID::BPRKS;
use YAML;

my $ibank = Finance::Bank::ID::BPRKS->new;
my $stmt;

if (@ARGV) {
    $stmt = [map {read_text($_)} @ARGV];
} else {
    $stmt = join "", <>;
}
print Dump $ibank->parse_statement($stmt, return_datetime_obj=>0);

1;
# ABSTRACT: Parse BPR KS internet banking statement
# PODNAME:

=head1 SYNOPSIS

 # for a single page
 % parse-bpr-statement < statement-page

 # for multiple pages
 % parse-bpr-statement page1.html page2.html ...


=head1 DESCRIPTION


=head1 SEE ALSO

L<Finance::Bank::ID::BPRKS>

=cut
